CREATE TABLE oms_order_review (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    shop_id BIGINT NOT NULL DEFAULT 1,
    order_id BIGINT NOT NULL,
    order_no VARCHAR(64) NOT NULL,
    user_id VARCHAR(64) NOT NULL,
    rating INT NOT NULL,
    content VARCHAR(500) NULL,
    image_urls TEXT NULL,
    request_id VARCHAR(64) NOT NULL,
    trace_id VARCHAR(64) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_oms_order_review_order FOREIGN KEY (order_id) REFERENCES oms_order (id),
    UNIQUE KEY uk_oms_order_review_shop_order (shop_id, order_id),
    UNIQUE KEY uk_oms_order_review_shop_user_request (shop_id, user_id, request_id),
    KEY idx_oms_order_review_shop_user_created (shop_id, user_id, created_at)
);
