<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.sangui.shop</groupId>
        <artifactId>sanguishop</artifactId>
        <version>0.1.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>sangui-services</artifactId>
    <packaging>pom</packaging>
    <name>SanguiShop Services</name>

    <modules>
        <module>sangui-gateway</module>
        <module>sangui-user-service</module>
        <module>sangui-product-service</module>
        <module>sangui-seckill-service</module>
        <module>sangui-order-service</module>
        <module>sangui-payment-service</module>
        <module>sangui-logistics-service</module>
        <module>sangui-review-service</module>
        <module>sangui-marketing-service</module>
        <module>sangui-search-rec-service</module>
        <module>sangui-ai-service</module>
    </modules>
</project>
