import {
  computed,
  ref,
  watch,
  type Ref,
} from 'vue'

export const appLocales = ['zh-Hans', 'zh-Hant', 'en'] as const
export type AppLocale = typeof appLocales[number]

export const appThemes = ['light', 'dark'] as const
export type AppTheme = typeof appThemes[number]

export interface AppPreferenceStorage {
  getItem(key: string): string | null
  setItem(key: string, value: string): void
}

interface PreferenceRoot {
  lang: string
  dataset: DOMStringMap
  style: CSSStyleDeclaration
}

interface PreferenceDocument {
  documentElement: PreferenceRoot
}

interface AppPreferenceOptions {
  storage?: AppPreferenceStorage
  document?: PreferenceDocument
}

export interface AppPreferences {
  locale: Ref<AppLocale>
  theme: Ref<AppTheme>
  localeLabel: Ref<string>
  themeLabel: Ref<string>
  setLocale(locale: AppLocale): void
  setTheme(theme: AppTheme): void
  toggleTheme(): void
  t(key: TranslationKey, params?: TranslationParams): string
  stop(): void
}

export type TranslationParams = Record<string, string | number>

const LOCALE_STORAGE_KEY = 'sangui.app.locale.v1'
const THEME_STORAGE_KEY = 'sangui.app.theme.v1'
const DEFAULT_LOCALE: AppLocale = 'zh-Hans'
const DEFAULT_THEME: AppTheme = 'light'

const zhHans = {
  'app.language': '语言',
  'app.theme': '主题',
  'app.theme.light': '浅色',
  'app.theme.dark': '深色',
  'app.locale.zhHans': '简中',
  'app.locale.zhHant': '繁中',
  'app.locale.en': 'English',
  'common.shopId': '店铺 ID',
  'common.usernameOrMobile': '用户名或手机号',
  'common.password': '密码',
  'common.signIn': '登录',
  'common.signingIn': '登录中...',
  'common.signOut': '退出登录',
  'common.refresh': '刷新',
  'common.refreshing': '刷新中...',
  'common.retry': '重试',
  'common.dismiss': '关闭',
  'common.prev': '上一页',
  'common.next': '下一页',
  'common.loading': '加载中...',
  'common.items': '{count} 项',
  'common.traceId': 'Trace ID',
  'common.code': 'code',
  'common.unknown': '未知',
  'mall.title': '商城',
  'mall.subtitle': '浏览上架商品，创建订单锁定库存，然后进入模拟支付。',
  'mall.loginFallback': '无法登录。',
  'mall.signedInAs': '用户 {userId} / 店铺 {shopId}',
  'mall.orders.kicker': '订单',
  'mall.orders.title': '最近购买',
  'mall.orders.loading': '正在加载订单...',
  'mall.orders.empty': '暂无订单。',
  'mall.orders.filterLabel': '订单状态筛选',
  'mall.orders.filterAll': '全部',
  'mall.orders.filterCreated': '待支付',
  'mall.orders.filterPaidAwaitingShipment': '待发货',
  'mall.orders.filterShipped': '已发货',
  'mall.orders.filterCancelled': '已取消',
  'mall.orders.filterUnknown': '未识别',
  'mall.orders.filterEmpty': '当前筛选下没有已加载订单。',
  'mall.orders.searchLabel': '按订单号或订单 ID 定位',
  'mall.orders.searchPlaceholder': '订单号或订单 ID',
  'mall.orders.searchAction': '定位',
  'mall.orders.searchNoCurrentPage': '当前页没有找到 {query}，可翻页继续查找，或从订单链接恢复详情。',
  'mall.orders.searchMatchedOrderNo': '已按订单号定位 {query}。',
  'mall.orders.searchMatchedOrderId': '已按订单 ID 定位 {query}。',
  'mall.orders.resultKicker': '状态',
  'mall.orders.resultTitle': '订单结果',
  'mall.orders.refreshOrder': '刷新订单',
  'mall.orders.refreshOrderHint': '刷新订单状态和物流信息',
  'mall.orders.refreshSuccess': '订单状态已更新。',
  'mall.orders.refreshFailedKeepDetail': '刷新失败，已保留当前订单详情。',
  'mall.orders.restoringDetail': '正在恢复订单详情...',
  'mall.orders.restoreErrorSuggestion': '订单可能不存在或当前账号无权查看，请返回最近购买确认。',
  'mall.orders.backToRecent': '查看最近购买',
  'mall.orders.clearOrderLink': '清除订单链接参数',
  'mall.orders.noOrderLink': '未使用订单链接',
  'mall.orders.invalidOrderLink': '订单链接中的 orderId 无效',
  'mall.orders.restoreFailedPrefix': '无法恢复订单 ',
  'mall.orders.restoreRecentSuggestion': '最近购买列表已保留，可清除链接参数后返回最近购买。',
  'mall.orders.loadingDetail': '正在加载订单详情...',
  'mall.orders.emptyDetail': '创建或选择一个订单。',
  'mall.orders.lastUpdated': '最后更新 {time}',
  'mall.orders.paymentStatus': '支付 {status}',
  'mall.orders.paymentRefreshAvailable': '支付状态可从支付单刷新：',
  'mall.orders.paymentFromOrderSnapshot': '支付状态来自订单快照，当前订单没有支付单号。',
  'mall.orders.paymentNoMissing': '缺少支付单号，无法刷新支付服务状态。',
  'mall.orders.paymentRefreshDisabledShipped': '订单已发货，支付刷新已关闭。',
  'mall.orders.paymentRefreshDisabledCancelled': '订单已取消，支付刷新已关闭。',
  'mall.orders.paymentRefreshUnknownPrefix': '未知订单状态：',
  'mall.orders.orderKicker': '订单 {orderId}',
  'mall.orders.pay': '模拟支付',
  'mall.orders.paying': '支付中...',
  'mall.orders.paid': '已支付',
  'mall.orders.refreshPayment': '刷新支付',
  'mall.orders.cancel': '取消未支付订单',
  'mall.orders.cancelling': '取消中...',
  'mall.orders.fulfillmentStatus': '履约 {status}',
  'mall.orders.statusCreated': '待支付',
  'mall.orders.statusPaid': '已支付',
  'mall.orders.statusPaidAwaitingShipment': '已支付，待发货',
  'mall.orders.statusCancelled': '已取消',
  'mall.orders.statusShipped': '已发货',
  'mall.orders.statusShippedSummary': '已发货，查看物流单号',
  'mall.orders.awaitingShipment': '待发货',
  'mall.orders.logisticsKicker': '物流',
  'mall.orders.logisticsTitle': '物流信息',
  'mall.orders.logisticsShippedMessage': '订单已发货，请使用下方承运商和物流单号跟进配送。',
  'mall.orders.logisticsAwaitingShipmentMessage': '订单已支付，商家正在准备发货，物流单号生成后会展示在这里。',
  'mall.orders.logisticsNotReadyMessage': '订单完成支付后，商家会安排发货。',
  'mall.orders.logisticsCancelledMessage': '订单已取消，无物流信息。',
  'mall.orders.logisticsUnknownMessage': '当前履约状态暂未识别，请稍后刷新订单。',
  'mall.orders.logisticsUnknownStatusPrefix': '未知履约状态：',
  'mall.orders.carrier': '承运商',
  'mall.orders.trackingNo': '物流单号',
  'mall.orders.shippedAt': '发货时间',
  'mall.orders.carrierPending': '承运商待补充',
  'mall.orders.trackingNoPending': '物流单号待补充',
  'mall.orders.shippedAtPending': '发货时间待补充',
  'mall.orders.lifecycleKicker': '进度',
  'mall.orders.lifecycleTitle': '订单进度',
  'mall.orders.lifecycleCreatedTitle': '订单已创建',
  'mall.orders.lifecycleCreatedDescription': '订单已生成，等待你完成支付。',
  'mall.orders.lifecyclePaidTitle': '支付完成',
  'mall.orders.lifecyclePaidDescription': '支付已完成，订单进入履约流程，等待商家发货。',
  'mall.orders.lifecycleShippedTitle': '订单已发货',
  'mall.orders.lifecycleShippedDescription': '平台当前只展示承运商和物流单号，不查询物流轨迹。',
  'mall.orders.lifecycleCancelledTitle': '订单已取消',
  'mall.orders.lifecycleCancelledDescription': '订单已取消，支付和发货动作都不可用。',
  'mall.orders.lifecycleUnknownTitle': '未知状态',
  'mall.orders.lifecycleUnknownPrefix': '后端状态 ',
  'mall.orders.lifecycleRefreshSuggestion': '请刷新订单确认最新结果。',
  'mall.orders.actionReady': '待支付订单可以模拟支付，也可以取消。',
  'mall.orders.actionPaymentComplete': '支付完成后订单进入履约流程。',
  'mall.orders.actionShipped': '订单已发货。',
  'mall.orders.actionCancelled': '订单已取消。',
  'mall.orders.actionUnknownPrefix': '未知订单状态：',
  'mall.orders.actionRefreshSuggestion': '请先刷新订单再操作。',
  'mall.cart.kicker': '购物车',
  'mall.cart.title': '草稿结算',
  'mall.cart.empty': '购物车为空。',
  'mall.cart.stockSnapshot': '{skuName} - 库存快照 {stock}',
  'mall.cart.remove': '移除',
  'mall.cart.clear': '清空购物车',
  'mall.cart.checkout': '结算购物车',
  'mall.cart.checkingOut': '结算中...',
  'mall.catalog.kicker': '商品目录',
  'mall.catalog.title': '商品',
  'mall.catalog.loading': '正在加载商品...',
  'mall.catalog.empty': '暂无上架商品。',
  'mall.catalog.loadFallback': '无法加载商品。',
  'mall.catalog.detailFallback': '无法加载商品详情。',
  'mall.catalog.stockOnDetail': '{status} / 库存见详情',
  'mall.catalog.productKicker': '商品 {productId}',
  'mall.catalog.skus': '{count} 个 SKU',
  'mall.catalog.selectProduct': '请选择商品。',
  'checkout.sku': 'SKU',
  'checkout.chooseVariant': '选择规格',
  'checkout.noSku': '未选择 SKU',
  'checkout.outOfStock': '缺货',
  'checkout.available': '可售 {count} 件',
  'checkout.left': '剩余 {count}',
  'checkout.quantity': '数量',
  'checkout.estimatedTotal': '预估小计',
  'checkout.signInRequired': '请先登录再创建订单。',
  'checkout.orderCreated': '订单 {orderNo}',
  'checkout.addToCart': '加入购物车',
  'checkout.buyNow': '立即购买',
  'checkout.creating': '创建中...',
  'checkout.created': '已创建订单',
  'ops.access': '运维访问',
  'ops.restoringSession': '正在恢复会话',
  'ops.restoringDescription': '正在检查最近一次补偿运维会话。',
  'ops.compensation': '补偿运维',
  'ops.dashboardTitle': '值班看板',
  'ops.signedInSummary': '已以 {username} 登录店铺 {shopId}。会话过期目标：{expiresAt}。',
  'ops.refreshSession': '刷新会话',
  'ops.loginKicker': '运维登录',
  'ops.loginTitle': '补偿运维访问',
  'ops.loginIntro': '使用已配置的运维管理员账号直接进入看板，不需要手动注入浏览器 token。',
  'ops.loginUserPlaceholder': 'ops-admin',
  'ops.passwordPlaceholder': '请输入密码',
  'ops.forbiddenKicker': '已认证但被拦截',
  'ops.forbiddenTitle': '无权访问补偿运维',
  'ops.forbiddenIntro': '当前会话属于店铺 {shopId} 的 {username}，但已不再具备所需运维权限。',
  'ops.retryRefresh': '重试刷新',
  'ops.forbiddenFallback': '当前会话已认证，但不再允许访问补偿运维。',
  'admin.workspaceLabel': '管理工作区导航',
  'admin.productWorkspace': '商品管理',
  'admin.orderWorkspace': '订单管理',
  'admin.fulfillmentWorkspace': '发货管理',
  'admin.compensationWorkspace': '补偿运维',
  'productAdmin.kicker': '商品管理',
  'productAdmin.title': '商品、SKU 与库存维护',
  'productAdmin.intro': '在 `/admin` 中维护上架状态、价格和可售库存，并保持 shop scope 兼容。',
  'productAdmin.newProduct': '新建商品',
  'productAdmin.refreshList': '刷新列表',
  'productAdmin.productStatus': '状态筛选',
  'productAdmin.statusAll': '全部状态',
  'productAdmin.statusDraft': '草稿',
  'productAdmin.statusActive': '上架',
  'productAdmin.statusInactive': '下架',
  'productAdmin.listEmpty': '当前没有可用商品。',
  'productAdmin.listTitle': '商品列表',
  'productAdmin.availableStock': '可售库存',
  'productAdmin.reservedStock': '预留库存',
  'productAdmin.detailLoading': '正在加载商品详情...',
  'productAdmin.saveProduct': '保存商品',
  'productAdmin.saving': '保存中...',
  'productAdmin.activate': '上架',
  'productAdmin.deactivate': '下架',
  'productAdmin.productName': '商品名',
  'productAdmin.productDescription': '商品描述',
  'productAdmin.invalidRequired': '必填项不能为空',
  'productAdmin.skuList': 'SKU 列表',
  'productAdmin.addSku': '添加 SKU',
  'productAdmin.skuCode': 'SKU code',
  'productAdmin.skuName': 'SKU 名称',
  'productAdmin.priceCent': '价格（分）',
  'productAdmin.removeSku': '移除 SKU',
  'productAdmin.adjustStock': '调整库存',
  'productAdmin.duplicateSku': 'SKU code 不能重复',
  'orderAdmin.kicker': '订单管理',
  'orderAdmin.title': '订单、支付与预留排障',
  'orderAdmin.intro': '按订单维度查看用户下单、库存预留、支付状态和 trace 信息。',
  'orderAdmin.refreshList': '刷新列表',
  'orderAdmin.statusFilter': '状态筛选',
  'orderAdmin.statusAll': '全部状态',
  'orderAdmin.statusCreated': '待支付',
  'orderAdmin.statusPaid': '已支付',
  'orderAdmin.statusCancelled': '已取消',
  'orderAdmin.statusShipped': '已发货',
  'orderAdmin.orderNo': '订单号',
  'orderAdmin.userId': '用户',
  'orderAdmin.fromTime': '开始时间',
  'orderAdmin.toTime': '结束时间',
  'orderAdmin.search': '查询订单',
  'orderAdmin.totalOrders': '共 {count} 个订单',
  'orderAdmin.listEmpty': '当前筛选条件下没有订单。',
  'orderAdmin.listTitle': '订单列表',
  'orderAdmin.pageLabel': '第 {page} / {total} 页',
  'orderAdmin.itemCount': '商品件数',
  'orderAdmin.paymentNo': '支付单号',
  'orderAdmin.detailEmptyTitle': '选择订单',
  'orderAdmin.detailEmptyMeta': '查看订单快照和链路状态',
  'orderAdmin.detailEmpty': '请选择一个订单查看详情。',
  'orderAdmin.refreshOrder': '刷新订单',
  'orderAdmin.refreshPayment': '刷新支付',
  'orderAdmin.cancelOrder': '取消未支付订单',
  'orderAdmin.cancelling': '取消中...',
  'orderAdmin.amount': '金额',
  'orderAdmin.status': '订单状态',
  'orderAdmin.reservationNo': '库存预留号',
  'orderAdmin.paymentStatus': '支付状态',
  'orderAdmin.itemsTitle': '商品快照',
  'orderAdmin.sku': 'SKU',
  'orderAdmin.quantity': '数量',
  'orderAdmin.unitPrice': '单价',
  'orderAdmin.lineTotal': '小计',
  'orderAdmin.timelineTitle': '状态流转',
  'orderAdmin.timelineIntro': '按后端记录的时间展示关键状态变化，便于排查支付、取消和发货链路。',
  'orderAdmin.timelineCreatedDescription': '订单已创建，库存预留已进入待支付窗口。',
  'orderAdmin.timelinePaidDescription': '支付已确认，订单进入待履约状态。',
  'orderAdmin.timelineCancelledDescription': '订单已取消，库存释放流程应已完成或正在补偿。',
  'orderAdmin.timelineShippedDescription': '订单已发货，物流单号由履约工作台维护。',
  'orderAdmin.timelineUnknownDescription': '后端返回了暂未识别的状态，请结合 traceId 排查。',
  'orderAdmin.cancelConfirmTitle': '确认取消订单',
  'orderAdmin.cancelConfirmBody': '将取消订单 {orderNo}。该动作会触发库存释放，请确认运营意图后再继续。',
  'orderAdmin.cancelConfirmAction': '确认取消',
  'fulfillmentAdmin.kicker': '发货履约',
  'fulfillmentAdmin.title': '发货、物流与履约',
  'fulfillmentAdmin.intro': '查看已支付待发货订单，填写承运商和物流单号，并让用户侧订单看到发货结果。',
  'fulfillmentAdmin.refreshList': '刷新列表',
  'fulfillmentAdmin.statusFilter': '履约状态',
  'fulfillmentAdmin.statusAll': '全部状态',
  'fulfillmentAdmin.statusUnshipped': '待发货',
  'fulfillmentAdmin.statusShipped': '已发货',
  'fulfillmentAdmin.orderStatusShipped': '已发货',
  'fulfillmentAdmin.search': '查询发货单',
  'fulfillmentAdmin.totalFulfillments': '共 {count} 个履约订单',
  'fulfillmentAdmin.listEmpty': '当前筛选条件下没有待处理履约订单。',
  'fulfillmentAdmin.listTitle': '发货列表',
  'fulfillmentAdmin.detailEmptyTitle': '选择履约订单',
  'fulfillmentAdmin.detailEmptyMeta': '查看发货快照和物流信息',
  'fulfillmentAdmin.detailEmpty': '请选择一个订单查看履约详情。',
  'fulfillmentAdmin.refreshDetail': '刷新详情',
  'fulfillmentAdmin.fulfillmentStatus': '履约状态',
  'fulfillmentAdmin.shippedAt': '发货时间',
  'fulfillmentAdmin.carrier': '承运商',
  'fulfillmentAdmin.trackingNo': '物流单号',
  'fulfillmentAdmin.shipOrder': '确认发货',
  'fulfillmentAdmin.shipping': '发货中...',
  'dashboard.kicker': '运维看板',
  'dashboard.title': '补偿历史控制台',
  'dashboard.intro': '展示订单和支付服务的补偿历史，支持真实筛选、分页和尝试记录钻取。',
  'dashboard.viewLabel': '补偿数据视图',
  'dashboard.payment': '支付',
  'dashboard.order': '订单',
  'dashboard.orderId': '订单 ID',
  'dashboard.paymentNo': '支付单号',
  'dashboard.trigger': '触发方式',
  'dashboard.result': '结果',
  'dashboard.operator': '操作人',
  'dashboard.from': '开始时间',
  'dashboard.to': '结束时间',
  'dashboard.runQuery': '执行查询',
  'dashboard.reset': '重置',
  'dashboard.replayTitle': '重放控制',
  'dashboard.replayIntro': '单条重放在卡片上执行；批量重放以当前页作为明确有界范围。',
  'dashboard.exportCurrentPage': '导出当前页',
  'dashboard.replayOperator': '重放操作人',
  'dashboard.bulkLimit': '批量上限',
  'dashboard.dryRun': 'Dry run',
  'dashboard.bulkRunning': '批量重放中...',
  'dashboard.runBulkDryRun': '执行批量 dry-run',
  'dashboard.runBulkReplay': '执行批量重放',
  'dashboard.bulkScope': '当前批量范围：{count} 条可见 {view} 记录。',
  'dashboard.auditKicker': '日志检索',
  'dashboard.auditTitle': '运维审计检索模板',
  'dashboard.auditIntro': '这些筛选面向 Kibana 或 Loki 中的结构化 `Ops audit event.` 日志，不查询补偿历史表。',
  'dashboard.auditShopId': '审计店铺 ID',
  'dashboard.auditTraceId': '审计 Trace ID',
  'dashboard.auditOperator': '审计操作人',
  'dashboard.auditAction': '审计动作',
  'dashboard.auditOutcome': '审计结果',
  'dashboard.openIn': '在 {platform} 打开',
  'dashboard.copyQuery': '复制查询',
  'dashboard.copied': '已复制',
  'dashboard.kibanaEnabled': '在 Kibana Discover 打开',
  'dashboard.kibanaDisabled': '设置 VITE_KIBANA_DISCOVER_URL 后启用',
  'dashboard.lokiEnabled': '在 Loki Explore 打开',
  'dashboard.lokiDisabled': '设置 VITE_LOKI_EXPLORE_URL 后启用',
  'dashboard.queryResult': '查询结果',
  'dashboard.noResponse': '尚未收到成功响应。',
  'dashboard.pageSize': '每页条数',
  'dashboard.pageLabel': '第 {page} / {total} 页',
  'dashboard.viewAuditTrail': '查看审计轨迹',
  'dashboard.fetching': '正在拉取补偿历史记录...',
  'dashboard.empty': '当前筛选条件没有匹配的补偿聚合记录。',
  'dashboard.lastTraceAnchor': '最后可见 trace 锚点：',
  'dashboard.allTriggers': '全部触发方式',
  'dashboard.manual': '手动',
  'dashboard.scheduler': '调度',
  'dashboard.allResults': '全部结果',
  'dashboard.failed': '失败',
  'dashboard.skipped': '跳过',
  'dashboard.cancelled': '已取消',
  'dashboard.settled': '已结算',
  'dashboard.allAuditActions': '全部审计动作',
  'dashboard.opsLogin': '运维登录',
  'dashboard.opsRefresh': '运维刷新',
  'dashboard.orderQuery': '订单查询',
  'dashboard.orderManualReplay': '订单手动重放',
  'dashboard.orderBulkReplay': '订单批量重放',
  'dashboard.paymentQuery': '支付查询',
  'dashboard.paymentManualReconcile': '支付手动对账',
  'dashboard.paymentBulkReconcile': '支付批量对账',
  'dashboard.allOutcomes': '全部结果',
  'dashboard.success': '成功',
  'dashboard.denied': '拒绝',
  'aggregate.orderCompensation': '订单补偿',
  'aggregate.paymentCompensation': '支付补偿',
  'aggregate.orderId': '订单 ID',
  'aggregate.userId': '用户 ID',
  'aggregate.reservation': '库存预留',
  'aggregate.amount': '金额',
  'aggregate.latestTrace': '最近 Trace',
  'aggregate.latestAttempt': '最近尝试',
  'aggregate.paymentId': '支付 ID',
  'aggregate.orderNo': '订单号',
  'aggregate.channel': '渠道',
  'aggregate.matchedAttempts': '匹配尝试：{count}',
  'aggregate.totalAttempts': '总尝试：{count}',
  'aggregate.operator': '操作人：{operator}',
  'aggregate.copyTrace': '复制 traceId',
  'aggregate.copiedTrace': '已复制 trace',
  'aggregate.manualReplay': '手动重放',
  'aggregate.replaying': '重放中...',
  'aggregate.viewAttemptDetail': '查看尝试详情',
  'timeline.attempt': '尝试 #{id}',
  'timeline.traceId': 'Trace ID',
  'timeline.trigger': '触发方式',
  'timeline.operator': '操作人',
  'timeline.errorCode': '错误码',
  'timeline.noReason': '本次尝试没有持久化脱敏原因。',
} as const

export type TranslationKey = keyof typeof zhHans

const zhHant: Record<TranslationKey, string> = {
  ...zhHans,
  'admin.workspaceLabel': '管理工作區導航',
  'admin.productWorkspace': '商品管理',
  'admin.orderWorkspace': '訂單管理',
  'admin.compensationWorkspace': '補償運維',
  'productAdmin.kicker': '商品管理',
  'productAdmin.title': '商品、SKU 與庫存維護',
  'productAdmin.intro': '在 `/admin` 中維護上架狀態、價格和可售庫存，並保持 shop scope 相容。',
  'productAdmin.newProduct': '新建商品',
  'productAdmin.refreshList': '刷新列表',
  'productAdmin.productStatus': '狀態篩選',
  'productAdmin.statusAll': '全部狀態',
  'productAdmin.statusDraft': '草稿',
  'productAdmin.statusActive': '上架',
  'productAdmin.statusInactive': '下架',
  'productAdmin.listEmpty': '目前沒有可用商品。',
  'productAdmin.listTitle': '商品列表',
  'productAdmin.availableStock': '可售庫存',
  'productAdmin.reservedStock': '預留庫存',
  'productAdmin.detailLoading': '正在載入商品詳情...',
  'productAdmin.saveProduct': '保存商品',
  'productAdmin.saving': '保存中...',
  'productAdmin.activate': '上架',
  'productAdmin.deactivate': '下架',
  'productAdmin.productName': '商品名',
  'productAdmin.productDescription': '商品描述',
  'productAdmin.invalidRequired': '必填項不能為空',
  'productAdmin.skuList': 'SKU 列表',
  'productAdmin.addSku': '新增 SKU',
  'productAdmin.skuCode': 'SKU code',
  'productAdmin.skuName': 'SKU 名稱',
  'productAdmin.priceCent': '價格（分）',
  'productAdmin.removeSku': '移除 SKU',
  'productAdmin.adjustStock': '調整庫存',
  'productAdmin.duplicateSku': 'SKU code 不能重複',
  'orderAdmin.statusShipped': '已發貨',
  'orderAdmin.timelineIntro': '按後端記錄的時間展示關鍵狀態變化，便於排查支付、取消和發貨鏈路。',
  'orderAdmin.timelineCreatedDescription': '訂單已建立，庫存預留已進入待支付窗口。',
  'orderAdmin.timelinePaidDescription': '支付已確認，訂單進入待履約狀態。',
  'orderAdmin.timelineCancelledDescription': '訂單已取消，庫存釋放流程應已完成或正在補償。',
  'orderAdmin.timelineShippedDescription': '訂單已發貨，物流單號由履約工作台維護。',
  'orderAdmin.timelineUnknownDescription': '後端返回了暫未識別的狀態，請結合 traceId 排查。',
  'orderAdmin.cancelConfirmTitle': '確認取消訂單',
  'orderAdmin.cancelConfirmBody': '將取消訂單 {orderNo}。該動作會觸發庫存釋放，請確認營運意圖後再繼續。',
  'orderAdmin.cancelConfirmAction': '確認取消',
  'app.language': '語言',
  'app.theme': '主題',
  'app.theme.light': '淺色',
  'app.theme.dark': '深色',
  'common.shopId': '店鋪 ID',
  'common.usernameOrMobile': '使用者名稱或手機號',
  'common.password': '密碼',
  'common.signIn': '登入',
  'common.signingIn': '登入中...',
  'common.signOut': '登出',
  'common.dismiss': '關閉',
  'common.prev': '上一頁',
  'common.next': '下一頁',
  'common.loading': '載入中...',
  'common.items': '{count} 項',
  'common.unknown': '未知',
  'mall.subtitle': '瀏覽上架商品，建立訂單鎖定庫存，然後進入模擬支付。',
  'mall.loginFallback': '無法登入。',
  'mall.signedInAs': '使用者 {userId} / 店鋪 {shopId}',
  'mall.orders.title': '最近購買',
  'mall.orders.loading': '正在載入訂單...',
  'mall.orders.empty': '暫無訂單。',
  'mall.orders.filterLabel': '訂單狀態篩選',
  'mall.orders.filterAll': '全部',
  'mall.orders.filterCreated': '待支付',
  'mall.orders.filterPaidAwaitingShipment': '待發貨',
  'mall.orders.filterShipped': '已發貨',
  'mall.orders.filterCancelled': '已取消',
  'mall.orders.filterUnknown': '未識別',
  'mall.orders.filterEmpty': '目前篩選下沒有已載入訂單。',
  'mall.orders.searchLabel': '按訂單號或訂單 ID 定位',
  'mall.orders.searchPlaceholder': '訂單號或訂單 ID',
  'mall.orders.searchAction': '定位',
  'mall.orders.searchNoCurrentPage': '目前頁面沒有找到 {query}，可翻頁繼續查找，或從訂單連結恢復詳情。',
  'mall.orders.searchMatchedOrderNo': '已按訂單號定位 {query}。',
  'mall.orders.searchMatchedOrderId': '已按訂單 ID 定位 {query}。',
  'mall.orders.resultTitle': '訂單結果',
  'mall.orders.refreshOrder': '刷新訂單',
  'mall.orders.refreshOrderHint': '刷新訂單狀態和物流資訊',
  'mall.orders.refreshSuccess': '訂單狀態已更新。',
  'mall.orders.refreshFailedKeepDetail': '刷新失敗，已保留目前訂單詳情。',
  'mall.orders.restoringDetail': '正在恢復訂單詳情...',
  'mall.orders.restoreErrorSuggestion': '訂單可能不存在或目前帳號無權查看，請返回最近購買確認。',
  'mall.orders.backToRecent': '查看最近購買',
  'mall.orders.clearOrderLink': '清除訂單連結參數',
  'mall.orders.noOrderLink': '未使用訂單連結',
  'mall.orders.invalidOrderLink': '訂單連結中的 orderId 無效',
  'mall.orders.restoreFailedPrefix': '無法恢復訂單 ',
  'mall.orders.restoreRecentSuggestion': '最近購買列表已保留，可清除連結參數後返回最近購買。',
  'mall.orders.loadingDetail': '正在載入訂單詳情...',
  'mall.orders.emptyDetail': '建立或選擇一個訂單。',
  'mall.orders.lastUpdated': '最後更新 {time}',
  'mall.orders.paymentRefreshAvailable': '支付狀態可從支付單刷新：',
  'mall.orders.paymentFromOrderSnapshot': '支付狀態來自訂單快照，目前訂單沒有支付單號。',
  'mall.orders.paymentNoMissing': '缺少支付單號，無法刷新支付服務狀態。',
  'mall.orders.paymentRefreshDisabledShipped': '訂單已發貨，支付刷新已關閉。',
  'mall.orders.paymentRefreshDisabledCancelled': '訂單已取消，支付刷新已關閉。',
  'mall.orders.paymentRefreshUnknownPrefix': '未知訂單狀態：',
  'mall.orders.cancel': '取消未支付訂單',
  'mall.orders.fulfillmentStatus': '履約 {status}',
  'mall.orders.statusCreated': '待支付',
  'mall.orders.statusPaid': '已支付',
  'mall.orders.statusPaidAwaitingShipment': '已支付，待發貨',
  'mall.orders.statusCancelled': '已取消',
  'mall.orders.statusShipped': '已發貨',
  'mall.orders.statusShippedSummary': '已發貨，查看物流單號',
  'mall.orders.awaitingShipment': '待發貨',
  'mall.orders.logisticsKicker': '物流',
  'mall.orders.logisticsTitle': '物流資訊',
  'mall.orders.logisticsShippedMessage': '訂單已發貨，請使用下方承運商和物流單號跟進配送。',
  'mall.orders.logisticsAwaitingShipmentMessage': '訂單已支付，商家正在準備發貨，物流單號生成後會展示在這裡。',
  'mall.orders.logisticsNotReadyMessage': '訂單完成支付後，商家會安排發貨。',
  'mall.orders.logisticsCancelledMessage': '訂單已取消，無物流資訊。',
  'mall.orders.logisticsUnknownMessage': '目前履約狀態暫未識別，請稍後刷新訂單。',
  'mall.orders.logisticsUnknownStatusPrefix': '未知履約狀態：',
  'mall.orders.carrier': '承運商',
  'mall.orders.trackingNo': '物流單號',
  'mall.orders.shippedAt': '發貨時間',
  'mall.orders.carrierPending': '承運商待補充',
  'mall.orders.trackingNoPending': '物流單號待補充',
  'mall.orders.shippedAtPending': '發貨時間待補充',
  'mall.orders.lifecycleKicker': '進度',
  'mall.orders.lifecycleTitle': '訂單進度',
  'mall.orders.lifecycleCreatedTitle': '訂單已建立',
  'mall.orders.lifecycleCreatedDescription': '訂單已生成，等待你完成支付。',
  'mall.orders.lifecyclePaidTitle': '支付完成',
  'mall.orders.lifecyclePaidDescription': '支付已完成，訂單進入履約流程，等待商家發貨。',
  'mall.orders.lifecycleShippedTitle': '訂單已發貨',
  'mall.orders.lifecycleShippedDescription': '平台目前只展示承運商和物流單號，不查詢物流軌跡。',
  'mall.orders.lifecycleCancelledTitle': '訂單已取消',
  'mall.orders.lifecycleCancelledDescription': '訂單已取消，支付和發貨動作都不可用。',
  'mall.orders.lifecycleUnknownTitle': '未知狀態',
  'mall.orders.lifecycleUnknownPrefix': '後端狀態 ',
  'mall.orders.lifecycleRefreshSuggestion': '請刷新訂單確認最新結果。',
  'mall.orders.actionReady': '待支付訂單可以模擬支付，也可以取消。',
  'mall.orders.actionPaymentComplete': '支付完成後訂單進入履約流程。',
  'mall.orders.actionShipped': '訂單已發貨。',
  'mall.orders.actionCancelled': '訂單已取消。',
  'mall.orders.actionUnknownPrefix': '未知訂單狀態：',
  'mall.orders.actionRefreshSuggestion': '請先刷新訂單再操作。',
  'mall.cart.kicker': '購物車',
  'mall.cart.empty': '購物車為空。',
  'mall.cart.clear': '清空購物車',
  'mall.cart.checkout': '結算購物車',
  'mall.catalog.kicker': '商品目錄',
  'mall.catalog.empty': '暫無上架商品。',
  'mall.catalog.selectProduct': '請選擇商品。',
  'checkout.chooseVariant': '選擇規格',
  'checkout.noSku': '未選擇 SKU',
  'checkout.outOfStock': '缺貨',
  'checkout.quantity': '數量',
  'checkout.estimatedTotal': '預估小計',
  'checkout.signInRequired': '請先登入再建立訂單。',
  'checkout.addToCart': '加入購物車',
  'checkout.buyNow': '立即購買',
  'checkout.created': '已建立訂單',
  'ops.loginKicker': '運維登入',
  'ops.loginTitle': '補償運維訪問',
  'ops.loginIntro': '使用已配置的運維管理員帳號直接進入看板，不需要手動注入瀏覽器 token。',
  'ops.passwordPlaceholder': '請輸入密碼',
  'ops.forbiddenKicker': '已認證但被攔截',
  'ops.forbiddenTitle': '無權訪問補償運維',
  'ops.forbiddenIntro': '目前會話屬於店鋪 {shopId} 的 {username}，但已不再具備所需運維權限。',
  'dashboard.title': '補償歷史控制台',
  'dashboard.intro': '展示訂單和支付服務的補償歷史，支援真實篩選、分頁和嘗試記錄鑽取。',
  'dashboard.runQuery': '執行查詢',
  'dashboard.exportCurrentPage': '匯出目前頁',
  'dashboard.auditTitle': '運維審計檢索模板',
  'dashboard.queryResult': '查詢結果',
  'dashboard.noResponse': '尚未收到成功響應。',
  'dashboard.pageLabel': '第 {page} / {total} 頁',
  'dashboard.viewAuditTrail': '查看審計軌跡',
  'dashboard.empty': '目前篩選條件沒有匹配的補償聚合記錄。',
  'aggregate.copiedTrace': '已複製 trace',
  'aggregate.viewAttemptDetail': '查看嘗試詳情',
  'timeline.errorCode': '錯誤碼',
  'timeline.noReason': '本次嘗試沒有持久化脫敏原因。',
}

const en: Record<TranslationKey, string> = {
  ...zhHans,
  'admin.workspaceLabel': 'Admin workspace navigation',
  'admin.productWorkspace': 'Product management',
  'admin.orderWorkspace': 'Order management',
  'admin.fulfillmentWorkspace': 'Fulfillment',
  'admin.compensationWorkspace': 'Compensation ops',
  'productAdmin.kicker': 'Product management',
  'productAdmin.title': 'Products, SKUs, and inventory maintenance',
  'productAdmin.intro': 'Maintain publish status, pricing, and sellable stock in `/admin` while keeping shop scope compatibility.',
  'productAdmin.newProduct': 'New product',
  'productAdmin.refreshList': 'Refresh list',
  'productAdmin.productStatus': 'Status filter',
  'productAdmin.statusAll': 'All statuses',
  'productAdmin.statusDraft': 'Draft',
  'productAdmin.statusActive': 'Active',
  'productAdmin.statusInactive': 'Inactive',
  'productAdmin.listEmpty': 'No products are available yet.',
  'productAdmin.listTitle': 'Product list',
  'productAdmin.availableStock': 'Available stock',
  'productAdmin.reservedStock': 'Reserved stock',
  'productAdmin.detailLoading': 'Loading product detail...',
  'productAdmin.saveProduct': 'Save product',
  'productAdmin.saving': 'Saving...',
  'productAdmin.activate': 'Activate',
  'productAdmin.deactivate': 'Deactivate',
  'productAdmin.productName': 'Product name',
  'productAdmin.productDescription': 'Product description',
  'productAdmin.invalidRequired': 'Required field cannot be empty',
  'productAdmin.skuList': 'SKU list',
  'productAdmin.addSku': 'Add SKU',
  'productAdmin.skuCode': 'SKU code',
  'productAdmin.skuName': 'SKU name',
  'productAdmin.priceCent': 'Price (cent)',
  'productAdmin.removeSku': 'Remove SKU',
  'productAdmin.adjustStock': 'Adjust stock',
  'productAdmin.duplicateSku': 'SKU code must be unique',
  'orderAdmin.kicker': 'Order management',
  'orderAdmin.title': 'Orders, payments, and reservations',
  'orderAdmin.intro': 'Inspect order snapshots, inventory reservations, payment status, and trace data by order.',
  'orderAdmin.refreshList': 'Refresh list',
  'orderAdmin.statusFilter': 'Status filter',
  'orderAdmin.statusAll': 'All statuses',
  'orderAdmin.statusCreated': 'Unpaid',
  'orderAdmin.statusPaid': 'Paid',
  'orderAdmin.statusCancelled': 'Cancelled',
  'orderAdmin.statusShipped': 'Shipped',
  'fulfillmentAdmin.kicker': 'Fulfillment',
  'fulfillmentAdmin.title': 'Shipment and logistics fulfillment',
  'fulfillmentAdmin.intro': 'Review paid orders awaiting shipment, enter carrier and tracking number, and expose shipment status to customers.',
  'fulfillmentAdmin.refreshList': 'Refresh list',
  'fulfillmentAdmin.statusFilter': 'Fulfillment status',
  'fulfillmentAdmin.statusAll': 'All statuses',
  'fulfillmentAdmin.statusUnshipped': 'Awaiting shipment',
  'fulfillmentAdmin.statusShipped': 'Shipped',
  'fulfillmentAdmin.orderStatusShipped': 'Shipped',
  'fulfillmentAdmin.search': 'Search fulfillments',
  'fulfillmentAdmin.totalFulfillments': '{count} fulfillment orders',
  'fulfillmentAdmin.listEmpty': 'No fulfillment orders match the current filters.',
  'fulfillmentAdmin.listTitle': 'Fulfillment list',
  'fulfillmentAdmin.detailEmptyTitle': 'Select a fulfillment',
  'fulfillmentAdmin.detailEmptyMeta': 'Inspect shipment snapshot and logistics details',
  'fulfillmentAdmin.detailEmpty': 'Select an order to view fulfillment detail.',
  'fulfillmentAdmin.refreshDetail': 'Refresh detail',
  'fulfillmentAdmin.fulfillmentStatus': 'Fulfillment status',
  'fulfillmentAdmin.shippedAt': 'Shipped at',
  'fulfillmentAdmin.carrier': 'Carrier',
  'fulfillmentAdmin.trackingNo': 'Tracking No',
  'fulfillmentAdmin.shipOrder': 'Ship order',
  'fulfillmentAdmin.shipping': 'Shipping...',
  'orderAdmin.orderNo': 'Order No',
  'orderAdmin.userId': 'User',
  'orderAdmin.fromTime': 'From',
  'orderAdmin.toTime': 'To',
  'orderAdmin.search': 'Search orders',
  'orderAdmin.totalOrders': '{count} orders',
  'orderAdmin.listEmpty': 'No orders match the current filters.',
  'orderAdmin.listTitle': 'Order list',
  'orderAdmin.pageLabel': 'Page {page} / {total}',
  'orderAdmin.itemCount': 'Items',
  'orderAdmin.paymentNo': 'Payment No',
  'orderAdmin.detailEmptyTitle': 'Select an order',
  'orderAdmin.detailEmptyMeta': 'View order snapshot and lifecycle state',
  'orderAdmin.detailEmpty': 'Select an order to inspect its detail.',
  'orderAdmin.refreshOrder': 'Refresh order',
  'orderAdmin.refreshPayment': 'Refresh payment',
  'orderAdmin.cancelOrder': 'Cancel unpaid order',
  'orderAdmin.cancelling': 'Cancelling...',
  'orderAdmin.amount': 'Amount',
  'orderAdmin.status': 'Order status',
  'orderAdmin.reservationNo': 'Reservation No',
  'orderAdmin.paymentStatus': 'Payment status',
  'orderAdmin.itemsTitle': 'Item snapshot',
  'orderAdmin.sku': 'SKU',
  'orderAdmin.quantity': 'Quantity',
  'orderAdmin.unitPrice': 'Unit price',
  'orderAdmin.lineTotal': 'Line total',
  'orderAdmin.timelineTitle': 'Status timeline',
  'orderAdmin.timelineIntro': 'Shows backend-recorded lifecycle changes for payment, cancellation, and shipment investigation.',
  'orderAdmin.timelineCreatedDescription': 'The order was created and inventory reservation entered the payment window.',
  'orderAdmin.timelinePaidDescription': 'Payment was confirmed and the order moved into fulfillment.',
  'orderAdmin.timelineCancelledDescription': 'The order was cancelled; inventory release should be complete or under compensation.',
  'orderAdmin.timelineShippedDescription': 'The order was shipped, with logistics fields maintained by the fulfillment workspace.',
  'orderAdmin.timelineUnknownDescription': 'The backend returned an unrecognized status; use the traceId for investigation.',
  'orderAdmin.cancelConfirmTitle': 'Confirm order cancellation',
  'orderAdmin.cancelConfirmBody': 'Cancel order {orderNo}. This can trigger inventory release, so continue only when the operator intent is clear.',
  'orderAdmin.cancelConfirmAction': 'Confirm cancellation',
  'app.language': 'Language',
  'app.theme': 'Theme',
  'app.theme.light': 'Light',
  'app.theme.dark': 'Dark',
  'common.shopId': 'Shop ID',
  'common.usernameOrMobile': 'Username or mobile',
  'common.password': 'Password',
  'common.signIn': 'Sign in',
  'common.signingIn': 'Signing in...',
  'common.signOut': 'Sign out',
  'common.refresh': 'Refresh',
  'common.refreshing': 'Refreshing...',
  'common.retry': 'Retry',
  'common.dismiss': 'Dismiss',
  'common.prev': 'Prev',
  'common.next': 'Next',
  'common.loading': 'Loading...',
  'common.items': '{count} items',
  'common.unknown': 'Unknown',
  'mall.title': 'Storefront',
  'mall.subtitle': 'Browse active catalog items, reserve stock through order creation, then enter mock payment.',
  'mall.loginFallback': 'Unable to sign in.',
  'mall.signedInAs': 'User {userId} / shop {shopId}',
  'mall.orders.kicker': 'Orders',
  'mall.orders.title': 'Recent purchases',
  'mall.orders.loading': 'Loading orders...',
  'mall.orders.empty': 'No orders yet.',
  'mall.orders.filterLabel': 'Order status filters',
  'mall.orders.filterAll': 'All',
  'mall.orders.filterCreated': 'Unpaid',
  'mall.orders.filterPaidAwaitingShipment': 'Awaiting shipment',
  'mall.orders.filterShipped': 'Shipped',
  'mall.orders.filterCancelled': 'Cancelled',
  'mall.orders.filterUnknown': 'Unrecognized',
  'mall.orders.filterEmpty': 'No loaded orders match this filter.',
  'mall.orders.searchLabel': 'Find by order number or order ID',
  'mall.orders.searchPlaceholder': 'Order number or order ID',
  'mall.orders.searchAction': 'Find',
  'mall.orders.searchNoCurrentPage': '{query} was not found on the current page. Continue paging, or restore detail from an order link.',
  'mall.orders.searchMatchedOrderNo': 'Located by order number {query}.',
  'mall.orders.searchMatchedOrderId': 'Located by order ID {query}.',
  'mall.orders.resultKicker': 'Status',
  'mall.orders.resultTitle': 'Order result',
  'mall.orders.refreshOrder': 'Refresh order',
  'mall.orders.refreshOrderHint': 'Refresh order status and logistics',
  'mall.orders.refreshSuccess': 'Order status has been updated.',
  'mall.orders.refreshFailedKeepDetail': 'Refresh failed. The current order detail is still shown.',
  'mall.orders.restoringDetail': 'Restoring order detail...',
  'mall.orders.restoreErrorSuggestion': 'The order may not exist or this account may not have access. Check recent purchases.',
  'mall.orders.backToRecent': 'View recent purchases',
  'mall.orders.clearOrderLink': 'Clear order link params',
  'mall.orders.noOrderLink': 'No order link is active',
  'mall.orders.invalidOrderLink': 'The orderId in the order link is invalid',
  'mall.orders.restoreFailedPrefix': 'Unable to restore order ',
  'mall.orders.restoreRecentSuggestion': 'Recent purchases are still available. Clear the link params to return to recent purchases.',
  'mall.orders.loadingDetail': 'Loading order detail...',
  'mall.orders.emptyDetail': 'Create or select an order.',
  'mall.orders.lastUpdated': 'Last updated {time}',
  'mall.orders.paymentStatus': 'Payment {status}',
  'mall.orders.paymentRefreshAvailable': 'Payment status can refresh from payment: ',
  'mall.orders.paymentFromOrderSnapshot': 'Payment status comes from the order snapshot because this order has no payment number.',
  'mall.orders.paymentNoMissing': 'Missing payment number, so payment-service status cannot be refreshed.',
  'mall.orders.paymentRefreshDisabledShipped': 'This order has shipped, so payment refresh is disabled.',
  'mall.orders.paymentRefreshDisabledCancelled': 'This order was cancelled, so payment refresh is disabled.',
  'mall.orders.paymentRefreshUnknownPrefix': 'Unknown order status: ',
  'mall.orders.orderKicker': 'Order {orderId}',
  'mall.orders.pay': 'Mock pay',
  'mall.orders.paying': 'Paying...',
  'mall.orders.paid': 'Paid',
  'mall.orders.refreshPayment': 'Refresh payment',
  'mall.orders.cancel': 'Cancel unpaid order',
  'mall.orders.cancelling': 'Cancelling...',
  'mall.orders.fulfillmentStatus': 'Fulfillment {status}',
  'mall.orders.statusCreated': 'Unpaid',
  'mall.orders.statusPaid': 'Paid',
  'mall.orders.statusPaidAwaitingShipment': 'Paid, awaiting shipment',
  'mall.orders.statusCancelled': 'Cancelled',
  'mall.orders.statusShipped': 'Shipped',
  'mall.orders.statusShippedSummary': 'Shipped, view tracking number',
  'mall.orders.awaitingShipment': 'Awaiting shipment',
  'mall.orders.logisticsKicker': 'Logistics',
  'mall.orders.logisticsTitle': 'Logistics',
  'mall.orders.logisticsShippedMessage': 'The order has shipped. Use the carrier and tracking number below to follow delivery.',
  'mall.orders.logisticsAwaitingShipmentMessage': 'The order is paid. The merchant is preparing shipment, and the tracking number will appear here when ready.',
  'mall.orders.logisticsNotReadyMessage': 'After payment is complete, the merchant will arrange shipment.',
  'mall.orders.logisticsCancelledMessage': 'This order was cancelled, so no logistics information is available.',
  'mall.orders.logisticsUnknownMessage': 'The current fulfillment status is not recognized. Refresh the order later.',
  'mall.orders.logisticsUnknownStatusPrefix': 'Unknown fulfillment status: ',
  'mall.orders.carrier': 'Carrier',
  'mall.orders.trackingNo': 'Tracking No',
  'mall.orders.shippedAt': 'Shipped at',
  'mall.orders.carrierPending': 'Carrier pending',
  'mall.orders.trackingNoPending': 'Tracking number pending',
  'mall.orders.shippedAtPending': 'Shipment time pending',
  'mall.orders.lifecycleKicker': 'Progress',
  'mall.orders.lifecycleTitle': 'Order progress',
  'mall.orders.lifecycleCreatedTitle': 'Order created',
  'mall.orders.lifecycleCreatedDescription': 'The order is created and waiting for payment.',
  'mall.orders.lifecyclePaidTitle': 'Payment complete',
  'mall.orders.lifecyclePaidDescription': 'Payment is complete and the order entered fulfillment, waiting for merchant shipment.',
  'mall.orders.lifecycleShippedTitle': 'Order shipped',
  'mall.orders.lifecycleShippedDescription': 'The platform currently shows only carrier and tracking number, without live tracking lookup.',
  'mall.orders.lifecycleCancelledTitle': 'Order cancelled',
  'mall.orders.lifecycleCancelledDescription': 'This order was cancelled. Payment and shipment actions are unavailable.',
  'mall.orders.lifecycleUnknownTitle': 'Unknown status',
  'mall.orders.lifecycleUnknownPrefix': 'Backend status ',
  'mall.orders.lifecycleRefreshSuggestion': 'Refresh the order to confirm the latest result.',
  'mall.orders.actionReady': 'This unpaid order can be paid or cancelled.',
  'mall.orders.actionPaymentComplete': 'Payment is complete and the order entered fulfillment.',
  'mall.orders.actionShipped': 'The order has shipped.',
  'mall.orders.actionCancelled': 'The order was cancelled.',
  'mall.orders.actionUnknownPrefix': 'Unknown order status: ',
  'mall.orders.actionRefreshSuggestion': 'Refresh the order before trying again.',
  'mall.cart.kicker': 'Cart',
  'mall.cart.title': 'Draft checkout',
  'mall.cart.empty': 'Cart is empty.',
  'mall.cart.stockSnapshot': '{skuName} - stock snapshot {stock}',
  'mall.cart.remove': 'Remove',
  'mall.cart.clear': 'Clear cart',
  'mall.cart.checkout': 'Checkout cart',
  'mall.cart.checkingOut': 'Checking out...',
  'mall.catalog.kicker': 'Catalog',
  'mall.catalog.title': 'Products',
  'mall.catalog.loading': 'Loading products...',
  'mall.catalog.empty': 'No active products.',
  'mall.catalog.loadFallback': 'Unable to load products.',
  'mall.catalog.detailFallback': 'Unable to load product detail.',
  'mall.catalog.stockOnDetail': '{status} / stock shown on detail',
  'mall.catalog.productKicker': 'Product {productId}',
  'mall.catalog.skus': '{count} SKUs',
  'mall.catalog.selectProduct': 'Select a product.',
  'checkout.chooseVariant': 'Choose variant',
  'checkout.noSku': 'No SKU selected',
  'checkout.outOfStock': 'Out of stock',
  'checkout.available': '{count} available',
  'checkout.left': '{count} left',
  'checkout.quantity': 'Quantity',
  'checkout.estimatedTotal': 'Estimated item total',
  'checkout.signInRequired': 'Sign in before creating an order.',
  'checkout.orderCreated': 'Order {orderNo}',
  'checkout.addToCart': 'Add to cart',
  'checkout.buyNow': 'Buy now',
  'checkout.creating': 'Creating...',
  'checkout.created': 'Order created',
  'ops.access': 'Ops access',
  'ops.restoringSession': 'Restoring session',
  'ops.restoringDescription': 'Checking the last compensation operations session.',
  'ops.compensation': 'Compensation ops',
  'ops.dashboardTitle': 'On-call dashboard',
  'ops.signedInSummary': 'Signed in as {username} for shop {shopId}. Session expiry target: {expiresAt}.',
  'ops.refreshSession': 'Refresh session',
  'ops.loginKicker': 'Ops sign-in',
  'ops.loginTitle': 'Compensation operations access',
  'ops.loginIntro': 'Use a configured ops admin account to enter the dashboard directly. No manual browser token injection is required.',
  'ops.passwordPlaceholder': 'Enter password',
  'ops.forbiddenKicker': 'Authenticated but blocked',
  'ops.forbiddenTitle': 'Compensation ops access denied',
  'ops.forbiddenIntro': 'The current session belongs to {username} in shop {shopId}, but it no longer has the required operations access.',
  'ops.retryRefresh': 'Retry refresh',
  'ops.forbiddenFallback': 'Current session is authenticated but no longer allowed to use compensation operations.',
  'dashboard.kicker': 'Ops dashboard',
  'dashboard.title': 'Compensation history console',
  'dashboard.intro': 'History-backed compensation records from order and payment services, wired for real filtering, paging, and attempt drill-down.',
  'dashboard.viewLabel': 'Compensation data views',
  'dashboard.payment': 'Payment',
  'dashboard.order': 'Order',
  'dashboard.orderId': 'Order ID',
  'dashboard.paymentNo': 'Payment No',
  'dashboard.trigger': 'Trigger',
  'dashboard.result': 'Result',
  'dashboard.operator': 'Operator',
  'dashboard.from': 'From',
  'dashboard.to': 'To',
  'dashboard.runQuery': 'Run query',
  'dashboard.reset': 'Reset',
  'dashboard.replayTitle': 'Replay controls',
  'dashboard.replayIntro': 'Manual replay runs per card. Bulk replay uses the current page as explicit bounded scope.',
  'dashboard.exportCurrentPage': 'Export current page',
  'dashboard.replayOperator': 'Replay operator',
  'dashboard.bulkLimit': 'Bulk limit',
  'dashboard.bulkRunning': 'Running bulk replay...',
  'dashboard.runBulkDryRun': 'Run bulk dry-run',
  'dashboard.runBulkReplay': 'Run bulk replay',
  'dashboard.bulkScope': 'Current bulk scope: {count} visible {view} record(s).',
  'dashboard.auditKicker': 'Log search',
  'dashboard.auditTitle': 'Ops audit search templates',
  'dashboard.auditIntro': 'These filters target structured `Ops audit event.` logs in Kibana or Loki. They do not query compensation history tables.',
  'dashboard.auditShopId': 'Audit shop ID',
  'dashboard.auditTraceId': 'Audit trace ID',
  'dashboard.auditOperator': 'Audit operator',
  'dashboard.auditAction': 'Audit action',
  'dashboard.auditOutcome': 'Audit outcome',
  'dashboard.openIn': 'Open in {platform}',
  'dashboard.copyQuery': 'Copy query',
  'dashboard.copied': 'Copied',
  'dashboard.kibanaEnabled': 'Open in Kibana Discover',
  'dashboard.kibanaDisabled': 'Set VITE_KIBANA_DISCOVER_URL to enable',
  'dashboard.lokiEnabled': 'Open in Loki Explore',
  'dashboard.lokiDisabled': 'Set VITE_LOKI_EXPLORE_URL to enable',
  'dashboard.queryResult': 'Query result',
  'dashboard.noResponse': 'No successful response received yet.',
  'dashboard.pageSize': 'Page size',
  'dashboard.pageLabel': 'Page {page} / {total}',
  'dashboard.viewAuditTrail': 'View audit trail',
  'dashboard.fetching': 'Fetching compensation history records...',
  'dashboard.empty': 'No compensation aggregate matched the current filter set.',
  'dashboard.lastTraceAnchor': 'Last visible trace anchor:',
  'dashboard.allTriggers': 'All triggers',
  'dashboard.manual': 'Manual',
  'dashboard.scheduler': 'Scheduler',
  'dashboard.allResults': 'All results',
  'dashboard.failed': 'Failed',
  'dashboard.skipped': 'Skipped',
  'dashboard.cancelled': 'Cancelled',
  'dashboard.settled': 'Settled',
  'dashboard.allAuditActions': 'All audit actions',
  'dashboard.opsLogin': 'Ops login',
  'dashboard.opsRefresh': 'Ops refresh',
  'dashboard.orderQuery': 'Order query',
  'dashboard.orderManualReplay': 'Order manual replay',
  'dashboard.orderBulkReplay': 'Order bulk replay',
  'dashboard.paymentQuery': 'Payment query',
  'dashboard.paymentManualReconcile': 'Payment manual reconcile',
  'dashboard.paymentBulkReconcile': 'Payment bulk reconcile',
  'dashboard.allOutcomes': 'All outcomes',
  'dashboard.success': 'Success',
  'dashboard.denied': 'Denied',
  'aggregate.orderCompensation': 'Order compensation',
  'aggregate.paymentCompensation': 'Payment compensation',
  'aggregate.orderId': 'Order ID',
  'aggregate.userId': 'User ID',
  'aggregate.reservation': 'Reservation',
  'aggregate.amount': 'Amount',
  'aggregate.latestTrace': 'Latest Trace',
  'aggregate.latestAttempt': 'Latest Attempt',
  'aggregate.paymentId': 'Payment ID',
  'aggregate.orderNo': 'Order No',
  'aggregate.channel': 'Channel',
  'aggregate.matchedAttempts': 'Matched attempts: {count}',
  'aggregate.totalAttempts': 'Total attempts: {count}',
  'aggregate.operator': 'Operator: {operator}',
  'aggregate.copyTrace': 'Copy traceId',
  'aggregate.copiedTrace': 'Copied trace',
  'aggregate.manualReplay': 'Manual replay',
  'aggregate.replaying': 'Replaying...',
  'aggregate.viewAttemptDetail': 'View attempt detail',
  'timeline.attempt': 'Attempt #{id}',
  'timeline.trigger': 'Trigger',
  'timeline.operator': 'Operator',
  'timeline.errorCode': 'Error Code',
  'timeline.noReason': 'No sanitized reason was persisted for this attempt.',
}

const translations: Record<AppLocale, Record<TranslationKey, string>> = {
  'zh-Hans': zhHans,
  'zh-Hant': zhHant,
  en,
}

let singleton: AppPreferences | null = null

export function useAppPreferences(): AppPreferences {
  if (!singleton) {
    singleton = createAppPreferences()
  }

  return singleton
}

export function createAppPreferences(options: AppPreferenceOptions = {}): AppPreferences {
  const storage = options.storage ?? getBrowserStorage()
  const targetDocument = options.document ?? getBrowserDocument()
  const locale = ref(readLocale(storage))
  const theme = ref(readTheme(storage))
  const localeLabel = computed(() => getLocaleLabel(locale.value))
  const themeLabel = computed(() => translateWithLocale(locale.value, theme.value === 'dark' ? 'app.theme.dark' : 'app.theme.light'))

  const stopWatch = watch([locale, theme], () => {
    writePreference(storage, LOCALE_STORAGE_KEY, locale.value)
    writePreference(storage, THEME_STORAGE_KEY, theme.value)
    applyDocumentPreferences(targetDocument, locale.value, theme.value)
  }, { immediate: true })

  function setLocale(nextLocale: AppLocale) {
    locale.value = nextLocale
  }

  function setTheme(nextTheme: AppTheme) {
    theme.value = nextTheme
  }

  function toggleTheme() {
    theme.value = theme.value === 'dark' ? 'light' : 'dark'
  }

  function t(key: TranslationKey, params: TranslationParams = {}): string {
    return interpolate(translateWithLocale(locale.value, key), params)
  }

  function stop() {
    stopWatch()
  }

  return {
    locale,
    theme,
    localeLabel,
    themeLabel,
    setLocale,
    setTheme,
    toggleTheme,
    t,
    stop,
  }
}

export function isAppLocale(value: string | null): value is AppLocale {
  return appLocales.some((locale) => locale === value)
}

export function isAppTheme(value: string | null): value is AppTheme {
  return appThemes.some((theme) => theme === value)
}

export function getLocaleLabel(locale: AppLocale): string {
  return translateWithLocale(DEFAULT_LOCALE, locale === 'zh-Hans'
    ? 'app.locale.zhHans'
    : locale === 'zh-Hant'
      ? 'app.locale.zhHant'
      : 'app.locale.en')
}

function readLocale(storage: AppPreferenceStorage | null): AppLocale {
  const stored = readPreference(storage, LOCALE_STORAGE_KEY)
  return isAppLocale(stored) ? stored : DEFAULT_LOCALE
}

function readTheme(storage: AppPreferenceStorage | null): AppTheme {
  const stored = readPreference(storage, THEME_STORAGE_KEY)
  return isAppTheme(stored) ? stored : DEFAULT_THEME
}

function readPreference(storage: AppPreferenceStorage | null, key: string): string | null {
  try {
    return storage?.getItem(key) ?? null
  } catch {
    return null
  }
}

function writePreference(storage: AppPreferenceStorage | null, key: string, value: string) {
  try {
    storage?.setItem(key, value)
  } catch {
    // Preference persistence is best-effort; the in-memory state still drives the UI.
  }
}

function translateWithLocale(locale: AppLocale, key: TranslationKey): string {
  return translations[locale][key] ?? translations[DEFAULT_LOCALE][key] ?? key
}

function interpolate(template: string, params: TranslationParams): string {
  return template.replace(/\{([a-zA-Z0-9_]+)\}/g, (match, key: string) => {
    const value = params[key]
    return value === undefined ? match : String(value)
  })
}

function applyDocumentPreferences(targetDocument: PreferenceDocument | null, locale: AppLocale, theme: AppTheme) {
  const root = targetDocument?.documentElement
  if (!root) {
    return
  }

  root.lang = localeToHtmlLang(locale)
  root.dataset.locale = locale
  root.dataset.theme = theme
  root.style.setProperty('color-scheme', theme)
}

function localeToHtmlLang(locale: AppLocale): string {
  if (locale === 'zh-Hant') {
    return 'zh-Hant'
  }
  if (locale === 'en') {
    return 'en'
  }

  return 'zh-CN'
}

function getBrowserStorage(): AppPreferenceStorage | null {
  if (typeof window === 'undefined') {
    return null
  }

  return window.localStorage
}

function getBrowserDocument(): PreferenceDocument | null {
  if (typeof document === 'undefined') {
    return null
  }

  return document
}
